spring:
  application:
    name: search-service
  profiles:
    active: dev
  config:
    import: nacos:search-service-dev.yml
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: yml
        group: DEV_GROUP
        namespace: dev