/**
 * 自动导入类型声明文件
 * 
 * 此文件由 unplugin-auto-import 插件自动生成
 * 用于声明全局可用的 API，无需手动 import 即可使用
 * 
 * 功能说明：
 * - Vue Composition API（ref, computed, reactive 等）
 * - Vue Router API（useRoute, useRouter 等）
 * - Pinia API（defineStore, storeToRefs 等）
 * - Element Plus 组件（ElMessage, ElMessageBox 等）
 * 
 * 使用方式：
 * 在 .vue 或 .ts 文件中可以直接使用这些函数，无需导入
 * 
 * 示例：
 * // 无需 import { ref } from 'vue'
 * const count = ref(0)  // 直接使用
 * 
 * // 无需 import { useRoute } from 'vue-router'
 * const route = useRoute()  // 直接使用
 * 
 * 注意：
 * - 此文件由工具自动生成，不应手动修改
 * - 如需修改自动导入配置，修改 vite.config.ts 中的 unplugin-auto-import 配置
 */

/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck：跳过 TypeScript 类型检查（因为是自动生成的文件）
// noinspection JSUnusedGlobalSymbols：忽略全局符号未使用的警告
// Generated by unplugin-auto-import：标记为工具自动生成
// biome-ignore lint: disable：禁用 biome linter 检查

/**
 * 空导出声明
 * 确保此文件作为模块而非脚本处理
 */
export {}

/**
 * 全局声明
 * 在全局作用域声明可用的常量和函数
 */
declare global {
  // ==================== Vue 核心 API ====================
  
  /** EffectScope：用于组织和管理响应式副作用的作用域 */
  const EffectScope: typeof import('vue').EffectScope
  
  /** computed：创建计算属性 */
  const computed: typeof import('vue').computed
  
  /** createApp：创建 Vue 应用实例 */
  const createApp: typeof import('vue').createApp
  
  /** customRef：创建自定义的响应式引用 */
  const customRef: typeof import('vue').customRef
  
  /** defineAsyncComponent：定义异步组件 */
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  
  /** defineComponent：定义组件（Setup 语法糖） */
  const defineComponent: typeof import('vue').defineComponent
  
  /** effectScope：创建 effect 作用域 */
  const effectScope: typeof import('vue').effectScope
  
  /** getCurrentInstance：获取当前组件实例 */
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  
  /** getCurrentScope：获取当前作用域 */
  const getCurrentScope: typeof import('vue').getCurrentScope
  
  /** h：创建虚拟 DOM 元素 */
  const h: typeof import('vue').h
  
  /** inject：注入依赖 */
  const inject: typeof import('vue').inject
  
  /** isProxy：检查是否是代理对象 */
  const isProxy: typeof import('vue').isProxy
  
  /** isReactive：检查是否是响应式对象 */
  const isReactive: typeof import('vue').isReactive
  
  /** isReadonly：检查是否是只读对象 */
  const isReadonly: typeof import('vue').isReadonly
  
  /** isRef：检查是否是 ref 对象 */
  const isRef: typeof import('vue').isRef
  
  /** isShallow：检查是否是浅层响应式 */
  const isShallow: typeof import('vue').isShallow
  
  /** markRaw：标记为非响应式 */
  const markRaw: typeof import('vue').markRaw
  
  /** nextTick：等待下一个 DOM 更新周期 */
  const nextTick: typeof import('vue').nextTick
  
  /** onMounted：组件挂载完成后调用 */
  const onMounted: typeof import('vue').onMounted
  
  /** provide：提供依赖 */
  const provide: typeof import('vue').provide
  
  /** reactive：创建响应式对象 */
  const reactive: typeof import('vue').reactive
  
  /** readonly：创建只读响应式对象 */
  const readonly: typeof import('vue').readonly
  
  /** ref：创建响应式引用 */
  const ref: typeof import('vue').ref
  
  /** resolveComponent：解析组件 */
  const resolveComponent: typeof import('vue').resolveComponent
  
  /** shallowReactive：创建浅层响应式对象 */
  const shallowReactive: typeof import('vue').shallowReactive
  
  /** shallowReadonly：创建浅层只读对象 */
  const shallowReadonly: typeof import('vue').shallowReadonly
  
  /** shallowRef：创建浅层响应式引用 */
  const shallowRef: typeof import('vue').shallowRef
  
  /** toRaw：获取原始对象 */
  const toRaw: typeof import('vue').toRaw
  
  /** toRef：创建基于响应式对象的引用 */
  const toRef: typeof import('vue').toRef
  
  /** toRefs：批量创建引用 */
  const toRefs: typeof import('vue').toRefs
  
  /** toValue：获取 ref 或 getter 的值 */
  const toValue: typeof import('vue').toValue
  
  /** triggerRef：手动触发 ref 更新 */
  const triggerRef: typeof import('vue').triggerRef
  
  /** unref：获取 ref 的值 */
  const unref: typeof import('vue').unref
  
  /** useAttrs：获取组件属性 */
  const useAttrs: typeof import('vue').useAttrs
  
  /** useCssModule：获取 CSS 模块 */
  const useCssModule: typeof import('vue').useCssModule
  
  /** useCssVars：使用 CSS 变量 */
  const useCssVars: typeof import('vue').useCssVars
  
  /** useId：生成唯一 ID */
  const useId: typeof import('vue').useId
  
  /** useModel：创建 model 响应式 */
  const useModel: typeof import('vue').useModel
  
  /** useSlots：获取插槽 */
  const useSlots: typeof import('vue').useSlots
  
  /** useTemplateRef：获取模板引用 */
  const useTemplateRef: typeof import('vue').useTemplateRef
  
  /** watch：监听响应式数据变化 */
  const watch: typeof import('vue').watch
  
  /** watchEffect：立即执行的响应式监听 */
  const watchEffect: typeof import('vue').watchEffect
  
  /** watchPostEffect：DOM 更新后执行的监听 */
  const watchPostEffect: typeof import('vue').watchPostEffect
  
  /** watchSyncEffect：同步执行的监听 */
  const watchSyncEffect: typeof import('vue').watchSyncEffect

  // ==================== Vue 生命周期钩子 ====================
  
  /** onActivated：keep-alive 组件激活时调用 */
  const onActivated: typeof import('vue').onActivated
  
  /** onBeforeMount：挂载前调用 */
  const onBeforeMount: typeof import('vue').onBeforeMount
  
  /** onBeforeUnmount：卸载前调用 */
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  
  /** onBeforeUpdate：更新前调用 */
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  
  /** onDeactivated：keep-alive 组件停用时调用 */
  const onDeactivated: typeof import('vue').onDeactivated
  
  /** onErrorCaptured：错误捕获时调用 */
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  
  /** onRenderTracked：渲染追踪时调用 */
  const onRenderTracked: typeof import('vue').onRenderTracked
  
  /** onRenderTriggered：渲染触发时调用 */
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  
  /** onScopeDispose：作用域销毁时调用 */
  const onScopeDispose: typeof import('vue').onScopeDispose
  
  /** onServerPrefetch：服务器端预取时调用 */
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  
  /** onUnmounted：卸载后调用 */
  const onUnmounted: typeof import('vue').onUnmounted
  
  /** onUpdated：更新后调用 */
  const onUpdated: typeof import('vue').onUpdated
  
  /** onWatcherCleanup：监听器清理时调用 */
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup

  // ==================== Vue Router API ====================
  
  /** onBeforeRouteLeave：路由离开前调用 */
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  
  /** onBeforeRouteUpdate：路由更新前调用 */
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  
  /** useLink：创建路由链接 */
  const useLink: typeof import('vue-router').useLink
  
  /** useRoute：获取当前路由对象 */
  const useRoute: typeof import('vue-router').useRoute
  
  /** useRouter：获取路由实例 */
  const useRouter: typeof import('vue-router').useRouter

  // ==================== Pinia 状态管理 API ====================
  
  /** acceptHMRUpdate：接受热更新 */
  const acceptHMRUpdate: typeof import('pinia').acceptHMRUpdate
  
  /** createPinia：创建 Pinia 实例 */
  const createPinia: typeof import('pinia').createPinia
  
  /** defineStore：定义 Store */
  const defineStore: typeof import('pinia').defineStore
  
  /** getActivePinia：获取当前 Pinia 实例 */
  const getActivePinia: typeof import('pinia').getActivePinia
  
  /** mapActions：映射 actions 到组件 */
  const mapActions: typeof import('pinia').mapActions
  
  /** mapGetters：映射 getters 到组件 */
  const mapGetters: typeof import('pinia').mapGetters
  
  /** mapState：映射 state 到组件 */
  const mapState: typeof import('pinia').mapState
  
  /** mapStores：映射 stores 到组件 */
  const mapStores: typeof import('pinia').mapStores
  
  /** mapWritableState：映射可写 state 到组件 */
  const mapWritableState: typeof import('pinia').mapWritableState
  
  /** setActivePinia：设置当前 Pinia 实例 */
  const setActivePinia: typeof import('pinia').setActivePinia
  
  /** setMapStoreSuffix：设置 map store 后缀 */
  const setMapStoreSuffix: typeof import('pinia').setMapStoreSuffix
  
  /** storeToRefs：将 store 转换为 refs */
  const storeToRefs: typeof import('pinia').storeToRefs

  // ==================== Element Plus 组件 ====================
  
  /** ElMessage：消息提示组件 */
  const ElMessage: typeof import('element-plus/es').ElMessage
  
  /** ElMessageBox：消息对话框组件 */
  const ElMessageBox: typeof import('element-plus/es').ElMessageBox
}

// ==================== 类型重导出 ====================

/**
 * 类型重导出声明
 * 从 vue 包导出常用的类型，供全局使用
 */
declare global {
  // @ts-ignore：跳过类型检查
  export type {
    /** 组件类型 */
    Component,
    /** 插槽类型 */
    Slot,
    /** 多个插槽类型 */
    Slots,
    /** 组件公开实例 */
    ComponentPublicInstance,
    /** 计算属性类型 */
    ComputedRef,
    /** 指令绑定类型 */
    DirectiveBinding,
    /** 提取组件默认属性类型 */
    ExtractDefaultPropTypes,
    /** 提取组件属性类型 */
    ExtractPropTypes,
    /** 提取公开属性类型 */
    ExtractPublicPropTypes,
    /** 注入键类型 */
    InjectionKey,
    /** 属性类型 */
    PropType,
    /** 引用类型 */
    Ref,
    /** 浅层引用类型 */
    ShallowRef,
    /** 可选引用类型 */
    MaybeRef,
    /** 可选引用或 getter 类型 */
    MaybeRefOrGetter,
    /** 虚拟节点类型 */
    VNode,
    /** 可写计算属性类型 */
    WritableComputedRef
  } from 'vue'
  
  // 从 vue 包导入类型
  import('vue')
}
